### PR TITLE
fix: filter cm fields not already present in resource

### LINKED ISSUE #143: argocd_cm: element "admin.enabled" has vanished
```
akp_instance.argocd: Modifying... [id=xxxxxxxxxxxx]
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to akp_instance.argocd, provider
│ "provider[\"registry.terraform.io/akuity/akp\"]" produced an unexpected new value: .argocd_cm: element
│ "admin.enabled" has vanished.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

While attempting to enable the admin user by setting `admin.enable = true` and adding `accounts.admin = login`, the `terraform apply` shows the error above. 

It seems that this is expected since the comment in the example states that "_once you add that, remove the "admin.enabled" key_". Introducing drift in the provider is a poor workflow for Terraform. The expectation that after enabling the `admin` user, it requires another change to the Terraform config to remove the `admin.enabled` key doesn't make sense. In a real-world use case, this would mean that the engineer would need to open a second PR to remove the key after the first change is accepted and applied.

**Proposal**: `admin.enabled` key should remain after it's set to `true` to avoid this confusing workflow and bug.

### PR DESCRIPTION
**Pull request by blakepettersson**
This would fix a lot of the inconsistent state issues which we see, where if we don't specify the exact keys that the API returns, the provider fails horribly. This also simplifies the config from a user perspective, since they don't have to specify every single key that the API returns. This means that from a TF perspective, the config becomes minimal in most cases.

This relies on the fact that when we submit requests to the ApplyConfig endpoint, that only the cm fields specified are set; any other field that needs to be present in the data model relies on the API to set the correct defaults.

Fixes #143

### CODE REVIEW

File: akp/types/configmap.go [hunk 1]
```diff
@@ -13,6 +13,44 @@ import (
...
 )
 
+func ToFilteredConfigMapTFModel(ctx context.Context, diagnostics *diag.Diagnostics, data *structpb.Struct, oldCM tftypes.Map) tftypes.Map {
+	if data == nil || len(data.AsMap()) == 0 {
+		if !oldCM.IsUnknown() && (oldCM.IsNull() || len(oldCM.Elements()) == 0) {
+			return oldCM
+		}
+	}
+
+	oldMap := make(map[string]interface{})
```
Comment (scarlson) [inline akp/types/configmap.go:23]:
```suggestion
	oldMap := make(map[string]interface{}, len(oldCM))
```
or similar, fewer alloc calls

Comment (blakepettersson) [reply akp/types/configmap.go]: done, thanks!

**Review by hanxiaop — APPROVED** [review]
LGTM. Can you also revise the doc comment to make it more precise? https://github.com/akuity/terraform-provider-akp/blob/16b5f2b79323614ea055d390a9c1c5c9e18e2483/examples/resources/akp_instance/resource.tf#L49-L52

**Comment by blakepettersson** [comment]
@hanxiaop thank you! How does this sound?

```
When configuring `argocd_cm`, there is generally no need to need to set all of these keys. If you do not set a key, the API will set suitable default values.
Please note that the API will disallow the setting of certain keys (such as "admin.enabled", or any key which isn't a known configuration option in `argocd-cm`).
```

**Comment by hanxiaop** [comment]
> @hanxiaop thank you! How does this sound?
> 
> > When configuring `argocd_cm`, there is generally no need to need to set all of these keys. If you do not set a key, the API will set suitable default values.
> > Please note that the API will disallow the setting of certain keys (such as "admin.enabled", or any key which isn't a known configuration option in `argocd-cm`).

@blakepettersson The `admin.enabled` can be set to false to disable the admin login. To enable the admin account, set `accounts.admin: "login"`, and to disable the admin login, set `admin.enabled: false`. They are mutually exclusive. Others looks great, thank you!

BTW the test has been fixed and I think the test can be passed after merge the current main branch.

File: docs/resources/instance.md [hunk 2]
```diff
@@ -148,11 +148,8 @@ resource "akp_instance" "example" {
     }
   }
   argocd_cm = {
-    # When configuring the `argocd_cm`, make sure to specify the following keys (from "admin.enabled", to "users.anonymous.enabled") since those keys are added by Akuity Platform by default.
-    # If they are not defined, you may see inconsistent results and errors from the provider.
-    # Feel free to customize the values based on your usage, but the keys themselves must be specified.
-    # Note that "admin.enabled" cannot be set to true independently, and an "accounts.admin" key is required, like the "accounts.alice" key below, once you add that, remove the "admin.enabled" key.
-    "admin.enabled"                  = false
+    # When configuring `argocd_cm`, there is generally no need to need to set all of these keys. If you do not set a key, the API will set suitable default values.
```
Comment (afzal442) [inline docs/resources/instance.md:151]:
```suggestion
    # When configuring `argocd_cm`, there is generally no need to set all of these keys. If you do not set a key, the API will set suitable default values.
```

File: examples/resources/akp_instance/resource.tf [hunk 3]
```diff
@@ -46,11 +46,8 @@ resource "akp_instance" "example" {
     }
   }
   argocd_cm = {
-    # When configuring the `argocd_cm`, make sure to specify the following keys (from "admin.enabled", to "users.anonymous.enabled") since those keys are added by Akuity Platform by default.
-    # If they are not defined, you may see inconsistent results and errors from the provider.
-    # Feel free to customize the values based on your usage, but the keys themselves must be specified.
-    # Note that "admin.enabled" cannot be set to true independently, and an "accounts.admin" key is required, like the "accounts.alice" key below, once you add that, remove the "admin.enabled" key.
-    "admin.enabled"                  = false
+    # When configuring `argocd_cm`, there is generally no need to need to set all of these keys. If you do not set a key, the API will set suitable default values.
```
Comment (afzal442) [inline examples/resources/akp_instance/resource.tf:49]:
```suggestion
    # When configuring `argocd_cm`, there is generally no need to set all of these keys. If you do not set a key, the API will set suitable default values.
```

**Review by afzal442 — CHANGES_REQUESTED** [review]
